### ISSUE TITLE
Memory Leak in Gradio UI

### ISSUE THREAD

**Issue by blazor67** [ace-step/ACE-Step#201]
There is a memory issue with the UI, where the ram used by the browser tab keeps on growing and the tab becomes increasingly unresponsive, until it fills up.
I have tried it on a local install and also in the Huggingface Space (https://huggingface.co/spaces/ACE-Step/ACE-Step) in both Firefox and Chrome, where the same issue happens everytime.
To replicate just start using the app, generate one or two songs and watch as the ram keeps filling up.
Idk if there's any more info I can provide to help solve this issue.

**Comment by GeorgeDrb** [comment]
Yes, this issue does occur. I’ve noticed the same — after a few generations, the VRAM fills up. I resolved it by adding a cleanup_memory() function inside the pipeline_ace_step 

def cleanup_memory():
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    
    import gc
    gc.collect()

**Comment by trapf** [comment]
@GeorgeDrb would you mind creating a PR for this fix? I've had similar issues. My solution, as I am working with the `docker-compose.yml`, was to add this to the yml file:
```
[...]
environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
[...]
```

**Comment by GeorgeDrb** [comment]
[@trapf](https://github.com/trapf) I've implemented a `cleanup_memory()` method that's called after audio generation to explicitly free CUDA memory and collect garbage.

The PR for my implementation is here: [#209](https://github.com/ace-step/ACE-Step/pull/209)

**Comment by blazor67** [comment]
> [@trapf](https://github.com/trapf) I've implemented a `cleanup_memory()` method that's called after audio generation to explicitly free CUDA memory and collect garbage.
> 
> The PR for my implementation is here: [#209](https://github.com/ace-step/ACE-Step/pull/209)

I was able to test this out, but unfortunately the problem remains. Specifically, it's the system memory that keeps on filling up and not the VRAM. 
After some more testing I was also able to reproduce this issue by just uploading an audio in the audio2audio section, playing it, and then starting to write some text in the lyrics prompt (so without generating even once).

**Comment by GeorgeDrb** [comment]
Could you describe how quickly this occurs - after how many generations or how much time interacting with the interface? What total volumes of RAM usage do you observe after extended use of the application? In other words, what figures are we talking about - megabytes or gigabytes of RAM? Does the memory usage eventually plateau or does it grow indefinitely?

**Comment by allo-** [comment]
In a range that the Firefox tab begins to react slow and I stop using the previews to avoid having to reload and adjust all the changed settings again. My system has enough RAM and Firefox doesn't fill it completely even when it starts to become slow, so it is hard to tell how much it may be. I would say together with running ACE-Step and having a few usual desktop programs open it may be in the range up to around 1 GB before I stop using the previews in the browser, but that's only a rough estimate. And I think Firefox became less responsive without the RAM being completely full.

It may be worth to test with a server and a client PC and see if the problem lies completely in the browser. This may be a gradio bug (keeping references to the old audio around), or maybe even a Firefox bug. Zoom screen sharing also leaks quite a lot of memory with Firefox here.

**Comment by allo-** [comment]
> After some more testing I was also able to reproduce this issue by just uploading an audio in the audio2audio section, playing it, and then starting to write some text in the lyrics prompt (so without generating even once).

If you can reproduce with a minimal example, one could make a bug for the gradio project.

```python
import gradio as gr

def process_audio(audio_file):
    if audio_file is None:
        return "No audio uploaded."
    else:
        return str(audio_file)

iface = gr.Interface(
    fn=process_audio,
    inputs=gr.Audio(type="filepath", label="Upload Audio"),
    outputs=gr.Text(label="Result"),
    title="Example",
    description="Some example"
)

if __name__ == "__main__":
    iface.launch()
```

When adding music, playing, clearing and adding music again leads to a memleak with that example its a gradio or Firefox bug. The clear function should do what it says.

**Comment by blazor67** [comment]
> > After some more testing I was also able to reproduce this issue by just uploading an audio in the audio2audio section, playing it, and then starting to write some text in the lyrics prompt (so without generating even once).
> 
> If you can reproduce with a minimal example, one could make a bug for the gradio project.
> 
> import gradio as gr
> 
> def process_audio(audio_file):
>     if audio_file is None:
>         return "No audio uploaded."
>     else:
>         return str(audio_file)
> 
> iface = gr.Interface(
>     fn=process_audio,
>     inputs=gr.Audio(type="filepath", label="Upload Audio"),
>     outputs=gr.Text(label="Result"),
>     title="Example",
>     description="Some example"
> )
> 
> if __name__ == "__main__":
>     iface.launch()
> When adding music, playing, clearing and adding music again leads to a memleak with that example its a gradio or Firefox bug. The clear function should do what it says.

Yep, i was able to also reproduce the bug this way. 
Also respoding to @GeorgeDrb , after uploading the audio and playing it, the RAM started filling up after about 15 seconds. I've tested this in both Chrome and Firefox and got the same result. 
The graph below shows the ram climbing from 12gb used to around 20gb in 60 seconds. It doesn't go on forever, stopping and floating around 24-25gb used, but the tab eventually becomes completely unusable.
![Image](https://github.com/user-attachments/assets/f724c957-7500-4468-96d4-9aaa8d36c281)

**Comment by allo-** [comment]
Have a look in the gradio bug I just reported and give feedback there.
If disabling the waveform is a workaround that could be interesting for this bug, maybe as commandline flag, otherwise the main problem is with gradio.

**Comment by freddyaboulton** [comment]
Please let us know if disabling the waveform fixes the issue. also, can you share the audio files you're uploading when you encounter this bug?

**Comment by GeorgeDrb** [comment]
I did a little experiment in the following environment:

OS: Windows 11, Build: 24H2 (26100)
Browser: Chrome (Version 136.0.7103.114)
Python environment: Python 3.10.11, packages installed in the environment:
```
absl-py==2.2.2
accelerate==1.6.0
-e git+https://github.com/ace-step/ACE-Step@74121a5d8a9af2fd651ba70869e78868442f6329#egg=ace_step
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.11.18
aiosignal==1.3.2
annotated-types==0.7.0
anyio==4.9.0
async-timeout==5.0.1
attrs==25.3.0
audioread==3.0.1
blis==1.3.0
catalogue==2.0.10
certifi==2025.4.26
cffi==1.17.1
charset-normalizer==3.4.2
click==8.1.8
cloudpathlib==0.21.1
colorama==0.4.6
confection==0.1.5
contourpy==1.3.2
cutlet==0.5.0
cycler==0.12.1
cymem==2.0.11
datasets==3.4.1
decorator==5.2.1
diffusers==0.32.2
dill==0.3.8
docopt==0.6.2
einops==0.8.1
exceptiongroup==1.3.0
fastapi==0.115.12
ffmpy==0.5.0
filelock==3.13.1
flash_attn @ file:///E:/AceStep/flash_attn-2.7.4%252Bcu126torch2.6.0cxx11abiFALSE-cp310-cp310-win_amd64.whl#sha256=dad211664253bd8298bdb8493178f86a4ed0e81500b69655a86726c3d19555ad
fonttools==4.58.0
frozenlist==1.6.0
fsspec==2024.6.1
fugashi==1.4.0
gradio==5.29.1
gradio_client==1.10.1
groovy==0.1.2
grpcio==1.71.0
h11==0.16.0
hangul-romanize==0.1.0
httpcore==1.0.9
httpx==0.28.1
huggingface-hub==0.31.2
idna==3.10
importlib_metadata==8.7.0
jaconv==0.4.0
Jinja2==3.1.4
joblib==1.5.0
kiwisolver==1.4.8
langcodes==3.5.0
language_data==1.3.0
lazy_loader==0.4
librosa==0.11.0
lightning-utilities==0.14.3
llvmlite==0.44.0
loguru==0.7.3
marisa-trie==1.2.1
Markdown==3.8
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.10.1
mdurl==0.1.2
mojimoji==0.0.13
mpmath==1.3.0
msgpack==1.1.0
multidict==6.4.3
multiprocess==0.70.16
murmurhash==1.0.12
networkx==3.3
num2words==0.5.14
numba==0.61.2
numpy==2.1.2
orjson==3.10.18
packaging==25.0
pandas==2.2.3
peft==0.15.2
pillow==11.0.0
platformdirs==4.3.8
pooch==1.8.2
preshed==3.0.9
propcache==0.3.1
protobuf==6.31.0
psutil==7.0.0
py3langid==0.3.0
pyarrow==20.0.0
pycparser==2.22
pydantic==2.11.4
pydantic_core==2.33.2
pydub==0.25.1
Pygments==2.19.1
pyparsing==3.2.3
pypinyin==0.53.0
python-dateutil==2.9.0.post0
python-multipart==0.0.20
pytorch-lightning==2.5.1
pytz==2025.2
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
rich==14.0.0
ruff==0.11.10
safehttpx==0.1.6
safetensors==0.5.3
scikit-learn==1.6.1
scipy==1.15.3
semantic-version==2.10.0
shellingham==1.5.4
six==1.17.0
smart-open==7.1.0
sniffio==1.3.1
soundfile==0.13.1
soxr==0.5.0.post1
spacy==3.8.4
spacy-legacy==3.0.12
spacy-loggers==1.0.5
srsly==2.5.1
starlette==0.46.2
sympy==1.13.1
tensorboard==2.19.0
tensorboard-data-server==0.7.2
tensorboardX==2.6.2.2
thinc==8.3.6
threadpoolctl==3.6.0
tokenizers==0.21.1
tomlkit==0.13.2
torch==2.6.0+cu126
torchaudio==2.6.0+cu126
torchmetrics==1.7.1
torchvision==0.21.0+cu126
tqdm==4.67.1
transformers==4.50.0
triton-windows==3.2.0.post19
typer==0.15.4
typing-inspection==0.4.0
typing_extensions==4.13.2
tzdata==2025.2
unidic-lite==1.0.8
urllib3==2.4.0
uvicorn==0.34.2
wasabi==1.1.3
weasel==0.4.1
websockets==15.0.1
Werkzeug==3.1.3
win32_setctime==1.2.0
wrapt==1.17.2
xxhash==3.5.0
yarl==1.20.0
zipp==3.21.0
```

In total, I generated 44 tracks:
24 tracks using text-to-audio mode
20 tracks using audio-to-audio mode
```
2025-05-20 17:25:12.527 | INFO     | acestep.pipeline_ace_step:__call__:2063 - Generation #1 (text2music) completed in 64.41 seconds
2025-05-20 17:25:12.528 | INFO     | acestep.pipeline_ace_step:__call__:2064 -   - Diffusion: 61.47s, Audio conversion: 2.95s
2025-05-20 17:25:12.528 | INFO     | acestep.pipeline_ace_step:cleanup_memory:178 - Generation Statistics:
2025-05-20 17:25:12.529 | INFO     | acestep.pipeline_ace_step:cleanup_memory:179 -    Total: 1 generations, avg time: 64.41s
2025-05-20 17:25:12.529 | INFO     | acestep.pipeline_ace_step:cleanup_memory:184 -    Text to Audio: 1 generations, avg time: 64.41s
- - - - // - - - - 
2025-05-20 18:43:12.290 | INFO     | acestep.pipeline_ace_step:__call__:2063 - Generation #44 (text2music) completed in 59.32 seconds
2025-05-20 18:43:12.291 | INFO     | acestep.pipeline_ace_step:__call__:2064 -   - Diffusion: 56.30s, Audio conversion: 3.02s
2025-05-20 18:43:12.291 | INFO     | acestep.pipeline_ace_step:cleanup_memory:178 - Generation Statistics:
2025-05-20 18:43:12.291 | INFO     | acestep.pipeline_ace_step:cleanup_memory:179 -    Total: 44 generations, avg time: 48.54s
2025-05-20 18:43:12.292 | INFO     | acestep.pipeline_ace_step:cleanup_memory:184 -    Text to Audio: 24 generations, avg time: 63.93s
2025-05-20 18:43:12.292 | INFO     | acestep.pipeline_ace_step:cleanup_memory:188 -    Audio to Audio: 20 generations, avg time: 30.08s
```

The maximum RAM consumption by the browser was approximately 800MB, which occurred during track conversion. During track generation and playback, the average consumption was around 600MB.

I monitored RAM usage with a single browser tab open (containing only the application interface):
Before first track generation: 170MB
After first track generation: 250MB

Text-to-Audio generation (20 tracks):
After 10 tracks: 410MB
After 20 tracks: 470MB

Audio-to-Audio generation (20 tracks):
After 10 tracks: 660MB
After 20 tracks: 670MB

Final Text-to-Audio generation (4 tracks):
After 4 tracks: 620MB

I wasn't able to reproduce a significant memory leak. There was some memory growth, but it stayed within reasonable limits.
A larger test with more track generations might be needed to confirm, but I believe the results would be similar.
It seems like the memory issue could be specific to your local environment.

**Comment by allo-** [comment]
Did you play the previews each time? Without playing I do not have a leak at all. With playing the tab becomes slower and slower. Others have reported that loading and playing music without using ACE-Step at all makes the tab slow.


Probably gradio caches data that is loaded when playing the song in a way that the browser cannot free it.

**Comment by GeorgeDrb** [comment]
Yes, almost every generated track was played back - not in full, but in fragments. Of course, I might have skipped a few tracks) but the majority of the generated tracks were listened to.
